postgresql:
  enabled: false 

jdbcOverwrite:
  enable: true
  jdbcUrl: "jdbc:postgresql://dsq-rds-db.xxxx.ap-northeast-2.rds.amazonaws.com:5432/sonarqube"
  jdbcUsername: "postgres"
  jdbcPasswordSecret: "rds-sonar-secret"
  jdbcPasswordSecretKey: "password"

persistence:
  enabled: true
  storageClass: "gp3"
  size: 20Gi

ingress:
  enabled: false
