nameOverride: shopnow-user-service
image:
  repository: harbor.trongduong.space/shopnow/user-service
  tag: v1
service:
  port: 5865
  targetPort: 5865
configMap:
  enabled: true
  mountPath: /app/src/main/resources/application.properties
  data: |
    spring.application.name=user-service
    server.port=5865

    eureka.instance.hostname=user-service
    eureka.instance.instance-id=${spring.application.name}
    eureka.client.service-url.defaultZone=http://shopnow-discovery-server-service:8761/eureka/

    spring.datasource.url=jdbc:postgresql://dsq-rds-db.cdo6e2emyxdq.ap-northeast-2.rds.amazonaws.com:5432/postgres?useSSL=false
    spring.datasource.username=postgres

    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    # JWT/Keycloak configuration
    jwt.issuer_uri=http://shopnow-keycloak-realms-service:8080/realms/java-microservice-realm/protocol/openid-connect/token
    jwt.client_id=spring-cloud-client
    jwt.client_secret=AJufwN1eof8P5Gga5Y9atCFqdMuZEuKd
    jwt.grant_type=client_credentials
    jwt.scope=openid offline_access
targetGroupBinding:
  enabled: false