replicaCount: 1

image:
  repository: duongtrong27/biglab
  tag: shopnow-frontend-v1

service:
  port: 80
  targetPort: 80
configMap:
  enabled: false # Frontend thường build env vào code hoặc dùng Nginx config riêng
targetGroupBinding:
  enabled: true
  # Điền ARN của Target Group port 80 cho domain trongduong.space
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:993839006183:targetgroup/shopnow-fe-tg/e95fe81794d4e654